// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/actions/index.vue')['default']
    Avatar: typeof import('./src/components/avatar/index.vue')['default']
    CSSTest: typeof import('./src/views/CSSTest.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FullLogo: typeof import('./src/views/login/components/FullLogo.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Layout: typeof import('./src/views/Layout.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    LoginFrom: typeof import('./src/views/login/components/LoginFrom.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    OnlyLogo: typeof import('./src/components/sidebar/components/OnlyLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollerMenu: typeof import('./src/components/sidebar/components/ScrollerMenu.vue')['default']
    Setting: typeof import('./src/components/setting/index.vue')['default']
    SettingsIcon: typeof import('./src/components/Icons/SettingsIcon.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
  }
}
